name: CI Pipeline

on:
  push:
    branches: main

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout Code
       uses: actions/checkout@v3
       
     - name: Set up JDK
       uses: actions/setup-java@v3
       with:
         distribution: 'temurin'
         java-version: '17'

      - name: Build
        run: mvn clean compile
      
      - name: Run Tests
        run: mvn test
      
      - name: SonarQube Scan
        run: mvn sonar:sonar
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Push Docker Image
        run: |
          docker tag myapp:latest jfrog.io/myrepo.myapp:latest
          docker push jfroh.io/myrep/myapp:latest
          

        

        
         
